- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy dist content to backend server.
  # become: yes
  synchronize:
    src: "../../backend/dist/"
    dest: "~/web/"
    recursive: yes
    # owner: ubuntu
    # group: ubuntu

- name: start pm2 service.
  command: pm2 start -f ./main.js
  args:
    chdir: ~/web