- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: copy node_modules
  synchronize:
    src: "../../backend/node_modules"
    dest: "~/web"
    recursive: yes

- name: Copy dist content to backend server.
  synchronize:
    src: "../../backend/dist"
    dest: "~/web"
    recursive: yes

- name: start pm2 service.
  command: pm2 start -f ./main.js
  args:
    chdir: ~/web/dist