- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy dist content to backend servert.
  become: yes
  copy:
    src: "../../backend/dist/"
    dest: "~/web/"
    owner: ubuntu
    group: ubuntu

- name: Executing node
  shell: |
    pm2 start -f main.js
  args:
    chdir: ~/web