- name: Creates directory
  file:
    path: ~/web
    state: directory

# - name: copy node_modules
#   synchronize:
#     src: "../../backend/node_modules"
#     dest: "~/web"
#     recursive: yes

- name: Copy dist content to backend server.
  synchronize:
    src: "../../backend/"
    dest: "~/web/"
    recursive: yes

- name: start pm2 service.
  command: pm2 start -f ./main.js
  args:
    chdir: ~/web/dist
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"    