- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy dist content to s3 bucket.
  become: yes
  src: "../../backend/"
  dest: "~/web/"
  owner: ubuntu
  group: ubuntu

- name: Executing node
  shell: |
    pm2 start -f main.js
  args:
    chdir: ~/web/dist