version: 2.1
defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

# Here the start of the exercise from the course:
jobs:
  build_frontend:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm i
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build_backend:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            rm -rf node_modules/*
            npm i
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test_frontend:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Front-end test 
          command: |
            cd frontend
            npm i
            npm run test

  test_backend:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end test 
          command: |
            cd backend
            npm i
            npm run test

  scan_frontend:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Front-end scan & analyz 
          command: |
            cd frontend
            npm i
            npm audit --audit-level=critical
            npm audit fix --audit-level=critical --force

  scan_backend:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end scan & analyz 
          command: |
            cd backend
            npm i
            npm audit --audit-level=critical
            npm audit fix --audit-level=critical --force
            npm audit fix --force            

workflows:
  ci_pipeline_exercise:
    jobs:
      - build_frontend
      - build_backend
      - test_frontend:
          requires:
            - "build_frontend"
      - test_backend:
          requires:
            - "build_backend"
      - scan_frontend:
          requires:
            - "build_frontend"
      - scan_backend:
          requires:
            - "build_backend"            